
document.getElementById("imgstore").innerHTML = ""
function imageLoader_importImages(){
    document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/attack-available.png" id="GUI_attack-available"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/attack-unavailable.png" id="GUI_attack-unavailable"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/blank.png" id="GUI_blank"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/chat.png" id="GUI_chat"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/chromadelve-beta logo.png" id="GUI_chromadelve-beta logo"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/item frame.png" id="GUI_item frame"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/mapBG.png" id="GUI_mapBG"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/mvmntarrow-highlight-up.png" id="GUI_mvmntarrow-highlight-up"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/mvmntarrow-highlight.png" id="GUI_mvmntarrow-highlight"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/mvmntarrow-up.png" id="GUI_mvmntarrow-up"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/mvmntarrow.png" id="GUI_mvmntarrow"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/pause.png" id="GUI_pause"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/spellscroll.png" id="GUI_spellscroll"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/stats-back.png" id="GUI_stats-back"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/stats-front.png" id="GUI_stats-front"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/target-active.png" id="GUI_target-active"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/target-inactive.png" id="GUI_target-inactive"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/title/begin.png" id="GUI_title_begin"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/title/gamemenuscreen.png" id="GUI_title_gamemenuscreen"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/title/titlescreen.png" id="GUI_title_titlescreen"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/title/triple P logo.png" id="GUI_title_triple P logo"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/GUI/unpause.png" id="GUI_unpause"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/characters/debug-ghost-1.png" id="characters_debug-ghost-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/characters/debug-ghost-2.png" id="characters_debug-ghost-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/entities/testgoblin/testgoblin-2.png" id="entities_testgoblin_testgoblin-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/entities/testgoblin/testgoblin-attack.png" id="entities_testgoblin_testgoblin-attack"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/entities/testgoblin/testgoblin-hurt-1.png" id="entities_testgoblin_testgoblin-hurt-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/entities/testgoblin/testgoblin-hurt-2.png" id="entities_testgoblin_testgoblin-hurt-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/entities/testgoblin/testgoblin-hurt-3.png" id="entities_testgoblin_testgoblin-hurt-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/entities/testgoblin/testgoblin.png" id="entities_testgoblin_testgoblin"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/items/health-potion-i.png" id="items_health-potion-i"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/items/test.png" id="items_test"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/src/map-background.pixil" id="src_map-background"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/generic-floor.png" id="tiles_generic-floor"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/generic-wall.png" id="tiles_generic-wall"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/green-floor-1.png" id="tiles_green-floor-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/green-floor-2.png" id="tiles_green-floor-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/green-floor-3.png" id="tiles_green-floor-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/green-wall-1.png" id="tiles_green-wall-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/green-wall-2.png" id="tiles_green-wall-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/green-wall-3.png" id="tiles_green-wall-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/null.png" id="tiles_null"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/orange-floor-1.png" id="tiles_orange-floor-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/orange-floor-2.png" id="tiles_orange-floor-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/orange-floor-3.png" id="tiles_orange-floor-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/orange-wall-1.png" id="tiles_orange-wall-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/orange-wall-2.png" id="tiles_orange-wall-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/orange-wall-3.png" id="tiles_orange-wall-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/purple-floor-1.png" id="tiles_purple-floor-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/purple-floor-2.png" id="tiles_purple-floor-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/purple-floor-3.png" id="tiles_purple-floor-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/purple-wall-1.png" id="tiles_purple-wall-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/purple-wall-2.png" id="tiles_purple-wall-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/purple-wall-3.png" id="tiles_purple-wall-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/red-floor-1.png" id="tiles_red-floor-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/red-floor-2.png" id="tiles_red-floor-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/red-floor-3.png" id="tiles_red-floor-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/red-wall-1.png" id="tiles_red-wall-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/red-wall-2.png" id="tiles_red-wall-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="imgs/tiles/red-wall-3.png" id="tiles_red-wall-3"/>'
	}