
document.getElementById("imgstore").innerHTML = ""
function imageLoader_importImages(){
    document.getElementById("imgstore").innerHTML += '<img src="GUI/attack-available.png" id="GUI_attack-available"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/attack-unavailable.png" id="GUI_attack-unavailable"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/blank.png" id="GUI_blank"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/chat.png" id="GUI_chat"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/chromadelve-beta logo.png" id="GUI_chromadelve-beta logo"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/item frame.png" id="GUI_item frame"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/mapBG.png" id="GUI_mapBG"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/mvmntarrow-highlight-up.png" id="GUI_mvmntarrow-highlight-up"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/mvmntarrow-highlight.png" id="GUI_mvmntarrow-highlight"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/mvmntarrow-up.png" id="GUI_mvmntarrow-up"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/mvmntarrow.png" id="GUI_mvmntarrow"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/pause.png" id="GUI_pause"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/spellscroll.png" id="GUI_spellscroll"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/stats-back.png" id="GUI_stats-back"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/stats-front.png" id="GUI_stats-front"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/target-active.png" id="GUI_target-active"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/target-inactive.png" id="GUI_target-inactive"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/triple P logo.png" id="GUI_triple P logo"/>'
	document.getElementById("imgstore").innerHTML += '<img src="GUI/unpause.png" id="GUI_unpause"/>'
	document.getElementById("imgstore").innerHTML += '<img src="characters/debug-ghost-1.png" id="characters_debug-ghost-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="characters/debug-ghost-2.png" id="characters_debug-ghost-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="entities/testgoblin/testgoblin-2.png" id="entities_testgoblin_testgoblin-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="entities/testgoblin/testgoblin-attack.png" id="entities_testgoblin_testgoblin-attack"/>'
	document.getElementById("imgstore").innerHTML += '<img src="entities/testgoblin/testgoblin-hurt-1.png" id="entities_testgoblin_testgoblin-hurt-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="entities/testgoblin/testgoblin-hurt-2.png" id="entities_testgoblin_testgoblin-hurt-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="entities/testgoblin/testgoblin-hurt-3.png" id="entities_testgoblin_testgoblin-hurt-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="entities/testgoblin/testgoblin.png" id="entities_testgoblin_testgoblin"/>'
	document.getElementById("imgstore").innerHTML += '<img src="items/health-potion-i.png" id="items_health-potion-i"/>'
	document.getElementById("imgstore").innerHTML += '<img src="items/test.png" id="items_test"/>'
	document.getElementById("imgstore").innerHTML += '<img src="src/map-background.pixil" id="src_map-background"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/green-floor-1.png" id="tiles_green-floor-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/green-floor-2.png" id="tiles_green-floor-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/green-floor-3.png" id="tiles_green-floor-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/green-wall-1.png" id="tiles_green-wall-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/green-wall-2.png" id="tiles_green-wall-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/green-wall-3.png" id="tiles_green-wall-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/null.png" id="tiles_null"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/orange-floor-1.png" id="tiles_orange-floor-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/orange-floor-2.png" id="tiles_orange-floor-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/orange-floor-3.png" id="tiles_orange-floor-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/orange-wall-1.png" id="tiles_orange-wall-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/orange-wall-2.png" id="tiles_orange-wall-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/orange-wall-3.png" id="tiles_orange-wall-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/purple-floor-1.png" id="tiles_purple-floor-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/purple-floor-2.png" id="tiles_purple-floor-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/purple-floor-3.png" id="tiles_purple-floor-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/purple-wall-1.png" id="tiles_purple-wall-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/purple-wall-2.png" id="tiles_purple-wall-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/purple-wall-3.png" id="tiles_purple-wall-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/red-floor-1.png" id="tiles_red-floor-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/red-floor-2.png" id="tiles_red-floor-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/red-floor-3.png" id="tiles_red-floor-3"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/red-wall-1.png" id="tiles_red-wall-1"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/red-wall-2.png" id="tiles_red-wall-2"/>'
	document.getElementById("imgstore").innerHTML += '<img src="tiles/red-wall-3.png" id="tiles_red-wall-3"/>'
	}